# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc447e484d91c17f78b63a8909758d96e4ef6b3dedbb49b2bf44b91596112496db57af16271d80433df9e403557ba58d7d48a2cc6295bcec8fde6feefd10414

test:
  secret_key_base: 135bb9ffe54873e51d99879f654d8e631cbf72acbebd637622445bbba44bc6836ab54814b88ca6541eaf3059b2e93a33e01ab920bc6a389a6dd0467b51603965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
